<?php
require __DIR__ . '/bootstrap.php';
require dirname( __DIR__ ) . '/includes/class-ntc-formulas.php';
require dirname( __DIR__ ) . '/includes/class-ntc-renderer.php';
require dirname( __DIR__ ) . '/includes/class-ntc-rest.php';
require dirname( __DIR__ ) . '/includes/class-ntc-activator.php';
$fails = 0;
$assert = function ( $cond, $label ) use ( &$fails ) { if ( $cond ) { echo "ok   $label\n"; } else { echo "FAIL $label\n"; $fails++; } };
$assert( "'=SUM(A1)" === NTC_REST::guard_csv_cell( '=SUM(A1)' ), 'guard prefixes =' );
$assert( 'hello' === NTC_REST::guard_csv_cell( 'hello' ), 'guard passthrough' );
$assert( '-12.5' === NTC_REST::guard_csv_cell( '-12.5' ), 'guard keeps plain negative numbers' );
$GLOBALS['fake_slug_taken'] = true;
$repo = new NTC_Repository();
$repo->create_preset( 'table', 'My Style', array() );
$assert( 'my-style-2' === $GLOBALS['wpdb']->last_insert['slug'], 'slug collision suffixes -2' );
$GLOBALS['fake_slug_taken'] = false;
$repo->create_preset( 'table', 'My Style', array() );
$assert( 'my-style' === $GLOBALS['wpdb']->last_insert['slug'], 'free slug used as-is' );
NTC_Activator::deactivate();
$assert( 'ntc_sync_remote_datasets' === $GLOBALS['cleared_hook'], 'deactivate clears cron hook' );
$assert( $repo->set_source( 1, 'javascript:alert(1)' ), 'set_source returns true (normalizes)' );
$assert( '' === $GLOBALS['last_update'][0]['source_url'], 'set_source rejects non-http URL' );
$repo->set_source( 1, 'https://example.com/data.csv' );
$assert( 'https://example.com/data.csv' === $GLOBALS['last_update'][0]['source_url'], 'set_source accepts https URL' );
$repo->record_sync( 1, 'boom' );
$assert( 'boom' === $GLOBALS['last_update'][0]['source_error'], 'record_sync stores error' );
require dirname( __DIR__ ) . '/includes/class-ntc-sync.php';
$parsed = NTC_Sync::parse( $repo, "Name,Score\nA,10\nB,20", 'csv' );
$assert( 2 === count( $parsed['columns'] ) && 2 === count( $parsed['rows'] ), 'csv parse columns/rows' );
$assert( 'A' === $parsed['rows'][0][0], 'csv parse first cell' );
$GLOBALS['fake_http'] = array( 'response' => array( 'code' => 200 ), 'body' => "a,b\n1,2" );
$assert( "a,b\n1,2" === NTC_Sync::fetch( 'https://example.com/x.csv' ), 'fetch returns body' );
$GLOBALS['fake_http'] = array( 'response' => array( 'code' => 404 ), 'body' => '' );
$threw = false;
try { NTC_Sync::fetch( 'https://example.com/x.csv' ); } catch ( Throwable $e ) { $threw = true; }
$assert( $threw, 'fetch throws on 404' );
$r = ( new ReflectionClass( 'NTC_Renderer' ) )->newInstanceWithoutConstructor();
$call = function ( string $m, ...$a ) use ( $r ) { $mm = ( new ReflectionClass( 'NTC_Renderer' ) )->getMethod( $m ); $mm->setAccessible( true ); return $mm->invokeArgs( $r, $a ); };
$assert( '' === $call( 'schema_json', array( 'dataset_updated_at' => '2026-08-17 10:00:00' ), array( 'enableSchema' => false ), array() ), 'schema off returns empty' );
$schema = $call( 'schema_json', array( 'dataset_updated_at' => '2026-08-17 10:00:00', 'dataset_name' => 'Scores' ), array( 'enableSchema' => true, 'title' => 'Bench', 'valueColumns' => array( 1 ) ), array( array(), array( 'label' => 'Score', 'type' => 'number', 'unit' => 'fps' ) ) );
$assert( false !== strpos( $schema, '"@type":"Dataset"' ) && false !== strpos( $schema, 'variableMeasured' ), 'schema emits Dataset + variables' );
$assert( false === strpos( $schema, '</script><script' ), 'schema values escaped' );
$assert( '' === $call( 'updated_date_html', array( 'showUpdatedDate' => false ), array( 'dataset_updated_at' => 'x' ) ), 'updated date off returns empty' );
$assert( 'redbackground:url(x)' === $call( 'safe_css_value', 'red;background:url(x)' ), 'safe_css_value strips ; {}<>' );
$assert( '' === $call( 'css_length', '100%;background:red' ), 'css_length rejects injection' );
echo $fails ? "FAILURES: $fails\n" : "ALL PASS\n";
exit( $fails ? 1 : 0 );
